name: lumbar_rhythm
description: A free, local-first sitting and standing reminder app for lumbar health self-management.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
